version: '2.2'
volumes:
  jenkins-data:
  docker-in-docker-data:
services:
  jenkins:
    init: true
    image: samrocketman/demo-jenkins-world-2018:jenkins-server
    ports:
      - 8080:8080
    user: root
    command:
      - /bin/bash
      - -exc
      - |
        rm -f /var/run/docker.pid /var/run/docker/containerd/docker-containerd.pid
        nohup dockerd -D &
        until docker info &> /dev/null; do
            sleep 1
        done
        # preseed jenkins agent
        docker pull samrocketman/demo-jenkins-world-2018:jenkins-agent
        # preseed build dependencies for generating jobs to speed up demo
        su - -s /bin/bash jenkins -c '/bin/bash -exc "export JAVA_HOME=/opt/jdk; repo=https://github.com/samrocketman/demo-jenkins-world-2018-jenkins-bootstrap; [ -d demo-jenkins-world-2018-jenkins-bootstrap ] || git clone \$$repo; pushd \$${repo##*/}; ./gradlew -b gradle/jervis.gradle clean libs; popd; rm -rf \$${repo##*/}"'
        # create a reference repository
        [ -d ~jenkins/demo-reference-repo.git ] || su - -s /bin/bash jenkins -c '/bin/bash -exc "repo=demo-reference-repo.git; mkdir -p \$${repo};cd \$${repo}; git init --bare"'
        su - -s /bin/bash jenkins -c '/bin/bash -exc "cd demo-reference-repo.git; git fetch https://github.com/samrocketman/demo-jenkins-world-2018-jenkins-bootstrap +refs/*:refs/*"'
        su - -s /bin/bash jenkins -c '/bin/bash -exc "cd demo-reference-repo.git; git fetch https://github.com/samrocketman/jenkins-bootstrap-shared +refs/*:refs/*"'
        su - -s /bin/bash jenkins -c '/bin/bash -exc "cd demo-reference-repo.git; git fetch https://github.com/samrocketman/jervis +refs/*:refs/*"'
        # grant Jenkins access to use docker in docker
        grep 'docker:.*\bjenkins\b' /etc/group || sed -i 's/^\(docker:.*\)/\1jenkins/' /etc/group
        su - -s /bin/bash jenkins -c '/bin/bash -c "JAVA_HOME=/opt/jdk /run.sh"'
    privileged: true
    volumes:
      - 'jenkins-data:/var/lib/jenkins'
      - 'docker-in-docker-data:/var/lib/docker'
